### ISSUE TITLE
Possibly inverted "block" flag logic in recv function

### ISSUE THREAD

**Issue by barti2du** [rgrinberg/onanomsg#6]
I believe that passing _~block:true_ flag to
`recv ?(block=true) sock f`
function results in non-blocking opeartion and contrary _~block:false_ in the blocking one.

The native call
`C.nn_recv sock ba_start_p (Unsigned.Size_t.of_int (-1)) (int_of_bool block)`
will pass _1_ for _true_ (i.e. should block) into _nn_recv_ function, however _1_ corresponds to _NN_DONTWAIT_ (should not block) flag (defined in _nn.h_).

**Comment by vbmithr** [comment]
You're right. I did not spot the issue since I was only using the Lwt backend.
Fixed in 4d09e396e865ec2e73e0fa35f8fc53c8dfad3e68.
