### ISSUE TITLE
Device support

### ISSUE THREAD

**Issue by darioteixeira** [rgrinberg/onanomsg#9]
I know that adding support for devices is in TODO, and I'm guessing that if it were simple and obvious it would already be done.  Anyway, I'm evaluating ZeroMQ vs Nanomsg for a project, and device support is a major plus.  Is there an ETA on this?

**Comment by vbmithr** [comment]
We're not really working on this anymore. I tried to do a better binding at some point but could not make it work, I don't remember the reason.

I think nanomsg is simple and nicer to ZeroMQ. You should be able to add functionality if need be. I don't remember what is device support.

**Comment by vbmithr** [comment]
I see, I remember what a device is. It is probably not hard to add :)

**Comment by darioteixeira** [comment]
@vbmithr: thanks for the prompt reply!

> We're not really working on this anymore.

By *"this"* do you mean just device support or this project altogether?

And yes, I've been playing with both, and nanomsg does feel nicer than ZeroMQ.  Besides, all I've read suggests that nanomsg also has a better and cleaner design.

**Comment by rgrinberg** [comment]
While it's true that this library isn't actively being developed I'll still look at bug reports and feature requests.

@darioteixeira Is the support you're asking for is basically just binding http://nanomsg.org/v0.7/nn_device.3.html ? If that's the case then this should be fairly easy.

**Comment by darioteixeira** [comment]
> While it's true that this library isn't actively being developed I'll still look at bug reports and feature requests.

Good to hear!  Do you just happen to have no need for ONanomsg at the moment, or are there greener pastures somewhere else?  (Many people have migrated from Zeromq to Nanomsg; it's not crazy to think some upstart project takes them away from Nanomsg...)

> @darioteixeira Is the support you're asking for is basically just binding http://nanomsg.org/v0.7/nn_device.3.html ? If that's the case then this should be fairly easy.

I thought so too, but since it wasn't implemented I wondered if there was some tricky aspect that prevented a straightforward binding (I'm not familiar with Nanomsg's internals).

**Comment by rgrinberg** [comment]
> Good to hear! Do you just happen to have no need for ONanomsg at the moment, or are there greener pastures somewhere else?

I just have no use for nanomsg at the moment. I would definitely consider it though if I had a compelling use case.

**Comment by rgrinberg** [comment]
@darioteixeira `nn_device` are in master. Let us know if there's anything else you're missing.

**Comment by darioteixeira** [comment]
Wow, thanks!  I'm gonna try out most of the features of this lib. If I find anything missing I'll let you know...
